=== Laaliji/School-Management-System/static/xml/shema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="users"/>
                <xs:element ref="departments" minOccurs="1"/>
                <xs:element ref="filieres" minOccurs="1"/>
                <xs:element ref="matieres" minOccurs="1"/>
                <xs:element ref="students" minOccurs="1"/>
                <xs:element ref="professeurs" minOccurs="1"/>
                <xs:element ref="applications" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="user" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="user">
        <xs:complexType>
            <xs:attribute name="password" type="xs:string" use="required"/>
            <xs:attribute name="role" type="xs:string" use="required"/>
            <xs:attribute name="username" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="departments">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="department" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="department">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="filieres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="filiere" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="filiere">
        <xs:complexType>
            <xs:attribute name="department" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="matieres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="matiere" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="matiere">
        <xs:complexType>
            <xs:attribute name="filiere" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="details"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="username" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="details">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fullname"/>
                <xs:element name="birthdate" type="xs:string" minOccurs="1"/>
                <xs:element name="tel" type="xs:string" minOccurs="1"/>
                <xs:element name="email" type="xs:string" minOccurs="1"/>
                <xs:element name="cin" type="xs:string" minOccurs="1"/>
                <xs:element name="cne" type="xs:string" minOccurs="1"/>
                <xs:element name="apoge" type="xs:decimal" minOccurs="1"/>
                <xs:element name="adresse" type="xs:string" minOccurs="1"/>
                <xs:element name="mark" type="xs:decimal" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fullname">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fname" type="xs:string" minOccurs="1"/>
                <xs:element name="lname" type="xs:string" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="professeurs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="professeur" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="professeur">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="details3"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="department" type="xs:string" use="required"/>
            <xs:attribute name="username" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="details2">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MoyRegio" type="xs:decimal"/>
                <xs:element name="MoyNatio" type="xs:decimal"/>
                <xs:element name="MoyGen" type="xs:decimal"/>
                <xs:element name="Classement" type="xs:integer"/>
                <xs:element name="Mention" type="xs:string"/>
                <xs:element name="Date" type="xs:date"/>
                <xs:element name="ville" type="xs:string"/>
           
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="applications">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="application" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="application">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="details2"/>
            </xs:sequence>
            <xs:attribute name="status" type="xs:string" use="required" />
            <xs:attribute name="student" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="details3">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fullname"/>
                <xs:element name="birthdate" type="xs:string" minOccurs="1"/>
                <xs:element name="tel" type="xs:string" minOccurs="1"/>
                <xs:element name="email" type="xs:string" minOccurs="1"/>
                <xs:element name="cin" type="xs:string" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Laaliji/School-Management-System/static/xml/DATA2.xml
<?xml version="1.0" encoding="UTF-8"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="shema2.xsd">
  <!-- Users -->
  <users>
    <user username="admin" password="adminpass" role="admin"/>
    <user password="profpass" role="professor" username="prof1"/>
    <user password="profpass2" role="professor" username="prof2"/>
    <user username="prof4" password="bayar" role="professor"/>
    <user username="stud55" password="abdo" role="student"/>
  <user username="cul12" password="basakri" role="professor"/></users>
  <!-- Departments -->
  <departments>
    <department id="2" name="Economie"/>
    <department id="3" name="Electrique"/>
    <!-- Add more departments as needed -->
    <department id="4" name="Informatique"/>
    <department id="5" name="Litterature"/>
  </departments>
  <!-- Filières (Study Programs) -->
  <filieres>
    <filiere id="101" name="Génie Informatique " department="4"/>
    <filiere id="102" name="Intelligence Artificielle" department="4"/>
    <filiere id="103" name="Techniques de Management" department="2"/>
    <filiere id="104" name="Genie Electrique" department="3"/>
    <!-- Add more filières as needed -->
    <filiere id="105" name="Langue arabe" department="5"/>
  </filieres>
  <!-- Courses (Matieres) -->
  <matieres>
    <matiere id="1001" name="Langage C" filiere="101"/>
    <matiere id="1002" name="Analyse Numérique 2" filiere="104"/>
    <matiere id="2001" name="Organisation des entreprises" filiere="103"/>
    <!-- Add more matieres as needed -->
    <matiere id="2002" name="Etudes islamiques" filiere="105"/>
  </matieres>
  <!-- Students -->
  <students>
    <student id="1" username="student1">
      <details>
        <fullname>
          <fname>Zakariae</fname>
          <lname>LAALIJI</lname>
        </fullname>
        <birthdate>2003-09-26</birthdate>
        <tel>0652199597</tel>
        <email>zakariae.laaliji@gmail.com</email>
        <cin>t320011</cin>
        <cne>R137304620</cne>
        <apoge>674532</apoge>
        <adresse>Hassania 2 Bloc B numéro 55 El Alia Mohammedia</adresse>
        <mark>14</mark>
      </details>
    </student>
    <student id="2" username="Ahmed_med">
      <details>
        <fullname>
          <fname>ahmed</fname>
          <lname>ahmed</lname>
        </fullname>
        <birthdate>2002-11-11</birthdate>
        <tel>912473928093</tel>
        <email>ahmed@gmail.com</email>
        <cin>k827921</cin>
        <cne>jdqwjk</cne>
        <apoge>93218</apoge>
        <adresse>street 1 apartment 6</adresse>
        <mark>0</mark>
      </details>
    </student>
    <student id="3" username="yahya12">
      <details>
        <fullname>
          <fname>yahya</fname>
          <lname>saoud</lname>
        </fullname>
        <birthdate>2002-01-03</birthdate>
        <tel>0681737129</tel>
        <email>yahya@gmail.com</email>
        <cin>l8251823</cin>
        <cne>K72961823</cne>
        <apoge>0901272</apoge>
        <adresse>street 2</adresse>
        <mark>0</mark>
      </details>
    </student>
  </students>
  <!-- Professeurs -->
  <professeurs>
    <professeur id="100" department="4" username="prof1">
      <details3>
        <fullname>
          <fname>Abderrahman</fname>
          <lname>Chekry</lname>
        </fullname>
        <birthdate>1985-11-01</birthdate>
        <tel>123456789</tel>
        <email>Chekry@example.com</email>
        <cin>XY987654</cin>
      </details3>
    </professeur>
    <professeur id="101" department="4" username="prof2">
      <details3>
        <fullname>
          <fname>Jamal</fname>
          <lname>BAKKAS</lname>
        </fullname>
        <birthdate>1975-07-03</birthdate>
        <tel>823498862</tel>
        <email>bakkas@example.com</email>
        <cin>k736127</cin>
      </details3>
    </professeur>
    <professeur id="102" department="4" username="prof3">
      <details3>
        <fullname>
          <fname>Khadija</fname>
          <lname>ARHID</lname>
        </fullname>
        <birthdate>1987-10-03</birthdate>
        <tel>823498862</tel>
        <email>arhid@example.com</email>
        <cin>kc36777</cin>
      </details3>
    </professeur>
    <!-- Add more professeurs as needed -->
    <professeur id="103" department="3" username="prof4">
      <details3>
        <fullname>
          <fname>Abdelouahed</fname>
          <lname>BAYAR</lname>
        </fullname>
        <birthdate>1963-04-06</birthdate>
        <tel>06543532367</tel>
        <email>bayar@gmail.com</email>
        <cin>T5764743</cin>
      </details3>
    </professeur>
  <professeur id="104" department="5" username="cul12"><details3><fullname><fname>mounir</fname><lname>bassakri</lname></fullname><birthdate>1969-03-12</birthdate><tel>237462378642</tel><email>basakri@yahoo.fr</email><cin>J8237428</cin></details3></professeur></professeurs>
  <!-- Student Applications -->
  <applications>
    <!-- Student 1 -->
    <application student="student1" status="acceptée">
      <details2>
        <MoyRegio>15.50</MoyRegio>
        <MoyNatio>17.10</MoyNatio>
        <MoyGen>16.20</MoyGen>
        <Classement>12</Classement>
        <Mention>Très Bien</Mention>
        <Date>2022-12-06</Date>
        <ville>safi</ville>
        <filiere>105</filiere>
      </details2>
    </application>
    <!-- Student 2 -->
    <application student="Ahmed_med" status="acceptée">
      <details2>
        <MoyRegio>14</MoyRegio>
        <MoyNatio>19</MoyNatio>
        <MoyGen>16</MoyGen>
        <Classement>14</Classement>
        <Mention>bien</Mention>
        <Date>2021-11-11</Date>
        <ville>Mohammedia</ville>
        <filiere>102</filiere>
      </details2>
    </application>
    <application student="yahya12" status="acceptée">
      <details2>
        <MoyRegio>12</MoyRegio>
        <MoyNatio>18</MoyNatio>
        <MoyGen>15</MoyGen>
        <Classement>20</Classement>
        <Mention>bien</Mention>
        <Date>2021-12-12</Date>
        <ville>mrakch</ville>
        <filiere>101</filiere>
      </details2>
    </application>
  </applications>
</school>
